---
- hosts: all
  become: true
  vars:
    debianUrl: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb"
    centosUrl: "https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-latest.el9.noarch.rpm"
  tasks:
  
    - name: Download deb/rpm file based on OS
      ansible.builtin.get_url:
        url: "{{ debianUrl if ansible_facts['os_family'] == 'Debian' else centosUrl }}"
        dest: "{{ '/tmp/zabbix-release_6.4-1+ubuntu24.04_all.deb' if ansible_facts['os_family'] == 'Debian' else '/tmp/zabbix-release-6.4-1.el9.noarch.rpm' }}"

    - name: Install Zabbix repository
      ansible.builtin.apt:
        deb: /tmp/zabbix-release_6.4-1+ubuntu24.04_all.deb
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Zabbix repository for Rocky Linux
      ansible.builtin.yum:
        name: /tmp/zabbix-release-6.4-1.el9.noarch.rpm
        state: present
      when: ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Rocky' or ansible_distribution == 'Centos'

    - name: Install Zabbix agent and plugins (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        name:
          - zabbix-agent2
          - 'zabbix-agent2-plugin-*'
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Zabbix agent and plugins (Rocky Linux)
      ansible.builtin.yum:
        name:
          - zabbix-agent2
          - 'zabbix-agent2-plugin-*'
        state: present
      when: ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Rocky' or ansible_distribution == 'Centos'
    
    - name: Restart and enable Zabbix agent service
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: restarted
        enabled: yes
